---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)
num_clients: 3
task: classification


dataset:
  name: remote_sensing
  num_clients: ${num_clients}
  partition: iid

model:
  _target_: None
  name: resnet
  version: 18

strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config

client:
  batch_size: 32
  task: 
